export const USER_DATA = {
  name: 'Cezary',
  surname: 'Demianiuk',
  image:
    'https://ipla.pluscdn.pl/dituel/cp/15/15xeaz1hgt2j6b1ofx24iqnm78m4bv8h.jpg',
  league: 3,
  score: 63,
  userHasPremium: true,
  lastActivity: '',
  form: 'Dobra forma',
  baseData: {
    age: 30,
    height: 182,
    weight: 78,
    location: 'Siedlce (Mazowieckie)',
    mainPosition: 'Napastnik',
    alternatePosition: 'Prawy pomocnik',
    betterLeg: 'Lewa',
  },
  statistics: {
    seasons: {
      number: '21/22',
      teams: [
        {
          name: 'Pogoń Siedlce',
          league: 3,
          season: 'Wiosna',
          matches: 9,
          goals: 6,
          goalsAverage: 0.7,
          minutesAverage: 77,
          minutes: 693,
        },
        {
          name: 'Olimpia Elbląg',
          league: 3,
          season: 'Wiosna',
          matches: 12,
          goals: 5,
          goalsAverage: 0.4,
          minutesAverage: 58,
          minutes: 696,
        },
        {
          name: 'Orlęta Radzyń Podlaski',
          league: 4,
          season: 'Jesień',
          matches: 19,
          goals: 11,
          goalsAverage: 0.6,
          minutesAverage: 61,
          minutes: 1159,
        },
      ],
    },
    experience: [
      {
        league: 3,
        seasons: 2,
        matches: 29,
        goals: 14,
      },
      {
        league: 4,
        seasons: 3,
        matches: 51,
        goals: 32,
      },
    ],
  },
}
