import LogoGornik from 'img/mock/team-gornik.png'
import LogoPogon from 'img/mock/team-pogon.png'
import LogoSiarka from 'img/mock/team-siarka.png'
import LogoSlask from 'img/mock/team-slask.png'
import LogoWisla from 'img/mock/team-wisla.png'
import LogoZnicz from 'img/mock/team-znicz.png'
import { TProfileMatches } from 'types/profile'
import { v4 as uuid } from 'uuid'

export const profileMatchesData: TProfileMatches[] = [
  {
    season: 'Wiosna 21/22',
    matches: [
      {
        id: uuid(),
        homeTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 3,
        },
        awayTeam: {
          name: 'Siarka Tarnobrzeg',
          logoUrl: LogoSiarka.src,
          mainTeam: false,
          score: 1,
        },
        competition: '3 liga',
        wideoUrl: 'fdfssfds',
        date: new Date('2022-02-22').toISOString(),
        status: 'win',
        minutes: 90,
        goals: 2,
        score: {
          value: 0.72,
          trend: 'up',
        },
        yellowCards: 0,
        redCards: 0,
        additional: 'Pierwszy skład',
      },
      {
        id: uuid(),
        homeTeam: {
          name: 'Znicz Pruszków',
          logoUrl: LogoZnicz.src,
          mainTeam: false,
          score: 0,
        },
        awayTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 0,
        },
        competition: '3 liga',
        date: new Date('2022-02-22').toISOString(),
        status: 'draw',
        minutes: 48,
        goals: 1,
        score: {
          value: 0.18,
          trend: 'down',
        },
        yellowCards: 0,
        redCards: 0,
        additional: 'Z ławki',
      },
      {
        id: uuid(),
        homeTeam: {
          name: 'Wisła Puławy',
          logoUrl: LogoWisla.src,
          mainTeam: false,
          score: 4,
        },
        awayTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 3,
        },
        competition: '3 liga',
        date: new Date('2022-02-22').toISOString(),
        status: 'loss',
        minutes: 0,
        goals: 0,
        yellowCards: 0,
        redCards: 0,
        additional: 'Ławka',
      },
      {
        id: uuid(),
        homeTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 1,
        },
        awayTeam: {
          name: 'Śląsk Wrocław II',
          logoUrl: LogoSlask.src,
          mainTeam: false,
          score: 0,
        },
        competition: '3 liga',
        date: new Date('2022-02-22').toISOString(),
        status: 'win',
        minutes: 90,
        goals: 1,
        score: {
          value: 1.26,
          trend: 'up',
        },
        yellowCards: 1,
        redCards: 0,
        additional: 'Pierwszy skład',
      },
      {
        id: uuid(),
        homeTeam: {
          name: 'Górnik Polkowice',
          logoUrl: LogoGornik.src,
          mainTeam: false,
          score: 2,
        },
        awayTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 2,
        },
        competition: '3 liga',
        date: new Date('2022-02-22').toISOString(),
        status: 'draw',
        minutes: 61,
        goals: 0,
        score: {
          value: 0.42,
          trend: 'down',
        },
        yellowCards: 0,
        redCards: 1,
        additional: 'Z ławki',
      },
    ],
    total: {
      minutes: 271,
      goals: 4,
      score: {
        value: 0.85,
        trend: 'up',
      },
      yellowCards: 1,
      redCards: 1,
    },
    avgMatch: {
      minutes: 94,
      goals: 0.8,
      score: {
        value: 0.27,
        trend: 'up',
      },
      yellowCards: 0.2,
      redCards: 0.2,
    },
  },
  {
    season: 'Jesień 21/22',
    matches: [
      {
        id: uuid(),
        homeTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 3,
        },
        awayTeam: {
          name: 'Siarka Tarnobrzeg',
          logoUrl: LogoSiarka.src,
          mainTeam: false,
          score: 1,
        },
        competition: '3 liga',
        wideoUrl: 'fdfssfds',
        date: new Date('2022-02-22').toISOString(),
        status: 'win',
        minutes: 90,
        goals: 2,
        score: {
          value: 0.72,
          trend: 'up',
        },
        yellowCards: 0,
        redCards: 0,
        additional: 'Pierwszy skład',
      },
      {
        id: uuid(),
        homeTeam: {
          name: 'Znicz Pruszków',
          logoUrl: LogoZnicz.src,
          mainTeam: false,
          score: 0,
        },
        awayTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 0,
        },
        competition: '3 liga',
        date: new Date('2022-02-22').toISOString(),
        status: 'draw',
        minutes: 48,
        goals: 1,
        score: {
          value: 0.18,
          trend: 'down',
        },
        yellowCards: 0,
        redCards: 0,
        additional: 'Z ławki',
      },
      {
        id: uuid(),
        homeTeam: {
          name: 'Wisła Puławy',
          logoUrl: LogoWisla.src,
          mainTeam: false,
          score: 4,
        },
        awayTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 3,
        },
        competition: '3 liga',
        date: new Date('2022-02-22').toISOString(),
        status: 'loss',
        minutes: 0,
        goals: 0,
        yellowCards: 0,
        redCards: 0,
        additional: 'Ławka',
      },
      {
        id: uuid(),
        homeTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 1,
        },
        awayTeam: {
          name: 'Śląsk Wrocław II',
          logoUrl: LogoSlask.src,
          mainTeam: false,
          score: 0,
        },
        competition: '3 liga',
        date: new Date('2022-02-22').toISOString(),
        status: 'win',
        minutes: 90,
        goals: 1,
        score: {
          value: 1.26,
          trend: 'up',
        },
        yellowCards: 1,
        redCards: 0,
        additional: 'Pierwszy skład',
      },
      {
        id: uuid(),
        homeTeam: {
          name: 'Górnik Polkowice',
          logoUrl: LogoGornik.src,
          mainTeam: false,
          score: 2,
        },
        awayTeam: {
          name: 'Pogoń Siedlce',
          logoUrl: LogoPogon.src,
          mainTeam: true,
          score: 2,
        },
        competition: '3 liga',
        date: new Date('2022-02-22').toISOString(),
        status: 'draw',
        minutes: 61,
        goals: 0,
        score: {
          value: 0.42,
          trend: 'down',
        },
        yellowCards: 0,
        redCards: 1,
        additional: 'Z ławki',
      },
    ],
    total: {
      minutes: 271,
      goals: 4,
      score: {
        value: 0.85,
        trend: 'up',
      },
      yellowCards: 1,
      redCards: 1,
    },
    avgMatch: {
      minutes: 94,
      goals: 0.8,
      score: {
        value: 0.27,
        trend: 'up',
      },
      yellowCards: 0.2,
      redCards: 0.2,
    },
  },
]
